### ISSUE TITLE
Cohesive header with xyz

### ISSUE THREAD

**Issue by p5150j** [frequency-chain/docs#101]
As we want both the xyz and docs site to feel as 1 site we need to align the header content to be such. 
See image below to see alignment issues (_top is xyz, bottom is docs site_)

<img width="1502" alt="Screenshot 2024-11-13 at 1 15 35 PM" src="https://github.com/user-attachments/assets/fb6b8fc5-2f38-4fd3-9935-62364b6c76c5">

**Comment by wilwade** [comment]
Closed by #105
