### ISSUE TITLE
Add Glossary Page

### ISSUE THREAD

**Issue by demisx** [frequency-chain/docs#5]
Add new public Glossary page to the main Frequency documentation site, so there is one location of domain language terms to reference and maintain moving forward. 

**Audience**: General public

Tasks:
- [ ] Create new Glossary page on [Frequency documentation](site https://github.com/LibertyDSNP/frequency-docs)
- [ ] Publish new Glossary page on the web https://docs.frequency.xyz
- [ ] Review all current documentation places and consolidate glossaries on the new Glossary page 

References:
- Frequency Documentation Organization Doc on Google Drive

**Comment by wilwade** [comment]
@demisx I think we should stick with Frequency specific stuff for the glossary. So I agree that we should leave those out.
